### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by pmd5700** [dlashua/govee2mqtt#1]
Hi, I'm very new to all of this, so it's entirley possible I'm doign something wrong, but when I get to this point: `python3 ./app.py -c ./`, I get the following error:
```
peter@NVR:~/govee2mqtt$ python3 ./app.py -c ./
INFO:root:Starting Application
Traceback (most recent call last):
  File "./app.py", line 31, in <module>
    govee_mqtt.GoveeMqtt(config)
  File "/home/peter/govee2mqtt/govee_mqtt.py", line 49, in __init__
    asyncio.run(self.start_govee_loop())
AttributeError: module 'asyncio' has no attribute 'run'
peter@NVR:~/govee2mqtt$
```

**Comment by dlashua** [comment]
Interesting. Which version of python are you running? (python3 -V)

**Comment by pmd5700** [comment]
3.6.9

**Comment by dlashua** [comment]
Ah ha! asyncio.run() was added in Python 3.7. So you'll need at least that version to run this. I'm developing in Python 3.8, so anything older than 3.8 may have issues. Once this is feature complete, I will look at supporting older versions of Python.
